apiVersion: v1
kind: Service
metadata:
  name: bakehouse-svc
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: bakehouse
  type: NodePort
status:
  loadBalancer: {}