- name: DevOps Project
  become: true
  hosts: all
  tasks:
    - name: Copy directory
      copy:
        src: ./k8s
        dest: /opt/

    - name: Run kubectl apply
      shell: "kubectl apply -f /opt/k8s"