- name: DevOps Project
  become: true
  hosts: all
  tasks:
    - name: Copy directory
      copy:
        src: /tmp/k8s
        dest: /tmp

    - name: Run kubectl apply
      shell: "kubectl apply -f /tmp/k8s"